disabled_rules:
  - type_name
  - identifier_name

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - fastlane
  - gems
  - vendor
  - External
  - derivedData
  - Submodules
  
line_length: 140
file_length: 500
